### ISSUE TITLE
Feature request: custom border radii

### ISSUE THREAD

**Issue by orestesgaolin** [lekanbar/custom_rounded_rectangle_border#1]
It would be awesome to be able to provide custom radii for each of the corners similarly as it is possible to set border sides.

By the way - thanks for sharing this handy library!

**Comment by orestesgaolin** [comment]
Closing as this is also possible this way:

```
            decoration: BoxDecoration(
              border: Border(),
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(8),
                bottomLeft: Radius.circular(8),
              ),
            ),
```

**Comment by lekanbar** [comment]
Hey @orestesgaolin, sorry I'm just seeing this. Happy to see that you were able to figure out the fix for your request! :)
